# IoT/netlify.toml

# Build settings
[build]
  # Directory for standard serverless functions (good practice to have)
  functions = "netlify/functions"
  # Directory for edge functions
  edge_functions = "netlify/edge-functions"

# Local development server settings
[dev]
  port = 8888

# This single rule directs all traffic under /v1/*
# to your main router file: index.ts
[[edge_functions]]
  function = "index"
  path = "/v1/*"