[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"
  
  # Publish directory (usually not needed for APIs)
  publish = "."

[dev]
  port = 8888

[[edge_functions]]
  function = "index"
  path = "/v1"

[[edge_functions]]
  function = "index"
  path = "/v1/*"