[build]
  command = "echo 'No build needed for edge functions'"
  publish = "."

[dev]
  port = 8888

[[edge_functions]]
  function = "index"
  path = "/v1"

[[edge_functions]]
  function = "student"
  path = "/v1/student/*"